spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/roamdeck
    username: admin
    password: password

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
  profiles:
    active: dev
ollama:
  base-url: http://localhost:11434
  model: qwen3:14b  
deepseek:
  base-url: https://api.deepseek.com/beta
  api-key: ${DEEPSEEK_API_KEY}
  model: deepseek-v4-pro